"""Add tables for item, recipe, collection_log

Revision ID: afedee811b2a
Revises: 68b7d6ac3ad4
Create Date: 2025-05-13 08:56:41.803459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afedee811b2a'
down_revision = '68b7d6ac3ad4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('sku', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('sku')
    )
    op.create_table('collection_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_sku', sa.Text(), nullable=True),
    sa.Column('quantity_collected', sa.Text(), nullable=True),
    sa.Column('collected_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['item_sku'], ['item.sku'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_log_id'), 'collection_log', ['id'], unique=False)
    op.create_table('recipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('craftable_item', sa.Text(), nullable=True),
    sa.Column('output_qty', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['craftable_item'], ['item.sku'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipe_ingredients',
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('item_sku', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_sku'], ['item.sku'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.PrimaryKeyConstraint('recipe_id', 'item_sku')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe_ingredients')
    op.drop_table('recipe')
    op.drop_index(op.f('ix_collection_log_id'), table_name='collection_log')
    op.drop_table('collection_log')
    op.drop_table('item')
    # ### end Alembic commands ###
